name: Pipeline Demo 
on:
  push:
    branches:
      - "**" # Matches all branches

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "🎉 GitHub Actions is running!"
 